# Generated by Django 4.2.7 on 2024-01-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_temperaturehumiditydata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturehumiditydata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
